package cubes.gui

import javax.swing.JFrame


//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;

fun main () {
    Controls()
}

class Controls  {

    private val controlPanel:JPanel

    init {
        val frame = JFrame("Controls")
        frame.defaultCloseOperation = JFrame.EXIT_ON_CLOSE

        controlPanel = MyPanel()
        //controlPanel.setOpaque(true) //content panes must be opaque

        frame.add( controlPanel)

        // Display the window.
        frame.pack()
        frame.isVisible = true
    }


    class MyPanel : JPanel() {
        private var button1:JButton
        private var button2:JButton
        private var button3:JButton
        private var slider1:JSlider
        private var slider2:JSlider
        private var slider3:JSlider
        private var selectShaderCombo:JComboBox<String>
        private var shaderLabel:JLabel

        init {
            //construct preComponents
            val jcomp7Items = arrayOf("circle", "square", "triangle", "flower", "rect", "ngon");

            //construct components
            button1 = JButton ("align");
            button2 = JButton ("move");
            button3 = JButton ("clickme");
            slider1 = JSlider (0, 20);
            slider2 = JSlider (0, 20);
            slider3 = JSlider (0, 20);
            selectShaderCombo = JComboBox (jcomp7Items);
            shaderLabel = JLabel ("shader");

            //set components properties
            slider1.setOrientation (JSlider.HORIZONTAL);
            slider1.setMinorTickSpacing (1);
            slider1.setMajorTickSpacing (5);
            slider1.setPaintTicks (true);
            slider1.setPaintLabels (true);
            slider2.setOrientation (JSlider.HORIZONTAL);
            slider2.setMinorTickSpacing (1);
            slider2.setMajorTickSpacing (5);
            slider2.setPaintTicks (true);
            slider2.setPaintLabels (true);
            slider3.setOrientation (JSlider.HORIZONTAL);
            slider3.setMinorTickSpacing (1);
            slider3.setMajorTickSpacing (5);
            slider3.setPaintTicks (true);
            slider3.setPaintLabels (true);

            //adjust size and set layout
            setPreferredSize ( Dimension (550, 300));
            setLayout (null);

            //add components
            add (button1);
            add (button2);
            add (button3);
            add (slider1);
            add (slider2);
            add (slider3);
            add (selectShaderCombo);
            add (shaderLabel);

            //set component bounds (only needed by Absolute Positioning)
            button1.setBounds (10, 15, 100, 20);
            button2.setBounds (10, 60, 100, 20);
            button3.setBounds (10, 100, 100, 20);
            slider1.setBounds (125, 5, 420, 45);
            slider2.setBounds (125, 55, 420, 40);
            slider3.setBounds (125, 95, 425, 45);
            selectShaderCombo.setBounds (130, 160, 100, 25);
            shaderLabel.setBounds (10, 155, 100, 25);
        }



    }

}